import numpy as np
from helpers.utils import proj_dist

def rectangle_corners(p1, p2, psize, extend=110):
    # Return the corners of the rectangle extending the given angstroms in both directions from the p1-p2 line.
    n = (p2[1] - p1[1], p1[0] - p2[0]) # Compute normal vector of p1-p2 line
    n_mag = (n[0] ** 2 + n[1] ** 2) ** 0.5
    # ERROR HANDLING: Prevent division by zero
    if n_mag < 1e-10:
        return [(int(p1[0]), int(p1[1])), (int(p2[0]), int(p2[1])), 
                (int(p2[0]), int(p2[1])), (int(p1[0]), int(p1[1]))]
    n_norm = (n[0] / n_mag, n[1] / n_mag) # Scale to 1px long
    return [(round(p1[0] + n_norm[0] * extend / psize), round(p1[1] + n_norm[1] * extend / psize)), 
            (round(p2[0] + n_norm[0] * extend / psize), round(p2[1] + n_norm[1] * extend / psize)), 
            (round(p2[0] - n_norm[0] * extend / psize), round(p2[1] - n_norm[1] * extend / psize)), 
            (round(p1[0] - n_norm[0] * extend / psize), round(p1[1] - n_norm[1] * extend / psize))]


def order_corners(c1, c2, c3, c4):
    # For a rotated rectangle generated by rectangle_corners, return the corners in the order:
    # leftmost, rightmost, bottommost, topmost
    if c1[0] > c2[0] and c1[1] < c2[1]: # First quadrant
        return c3, c1, c4, c2
    elif c1[0] > c2[0] and c1[1] > c2[1]: # Second quadrant
        return c2, c4, c3, c1
    elif c1[0] < c2[0] and c1[1] > c2[1]: # Third quadrant
        return c1, c3, c2, c4
    elif c1[0] < c2[0] and c1[1] < c2[1]: # Fourth quadrant
        return c4, c2, c1, c3
    else:
        raise Exception(f"Two (or more) corners have equal coordinates: {c1}, {c2}, {c3}, {c4}")


def rectangle_ylimit(c_left, c_right, c_between, slope_left_to_mid, slope_mid_to_right, x):
    # For the adjacent rectangle sides from c_left to a midpoint to c_right (its "top side" or "bottom side"),
    # return the rectangle's y-coordinate at the given x-coordinate
    assert (c_left[0] <= x <= c_right[0])
    if x < c_between[0]: # On line from c_left to c_between
        return round(c_left[1] + (x - c_left[0]) * slope_left_to_mid)
    # On line from c_between to c_right
    return round(c_between[1] + (x - c_between[0]) * slope_mid_to_right)


def points_in_rectangle(c1, c2, c3, c4):
    # Precondition: Corners given in anticlockwise order

    n = (c1[1] - c2[1], c2[0] - c1[0]) # Normal vector to edge
    if n[1] == 0: # Short side is vertical
        min_x, max_x = min(c1[0], c3[0]), max(c1[0], c3[0])
        min_y, max_y = min(c1[1], c2[1]), max(c1[1], c2[1])
        return [(x, y) for x in range(min_x, max_x + 1) for y in range(min_y, max_y + 1)]
    elif n[0] == 0: # Short side is horizontal
        min_x, max_x = min(c1[0], c2[0]), max(c1[0], c2[0])
        min_y, max_y = min(c1[1], c3[1]), max(c1[1], c3[1])
        return [(x, y) for x in range(min_x, max_x + 1) for y in range(min_y, max_y + 1)]
    # else: rectangle is at some slant
    c_left, c_right, c_bottom, c_top = order_corners(c1, c2, c3, c4)

    # ERROR HANDLING: when a corner shares an x with its neighbour the edge is vertical
    # and that slope's x-range is empty (so the value is never used by rectangle_ylimit);
    # default it to 0.0 to avoid a spurious ZeroDivisionError near axis-aligned segments.
    def _slope(num, den):
        return num / den if den != 0 else 0.0

    slope_left_to_bottom = _slope(c_bottom[1] - c_left[1], c_bottom[0] - c_left[0])
    slope_bottom_to_right = _slope(c_right[1] - c_bottom[1], c_right[0] - c_bottom[0])
    slope_left_to_top = _slope(c_top[1] - c_left[1], c_top[0] - c_left[0])
    slope_top_to_right = _slope(c_right[1] - c_top[1], c_right[0] - c_top[0])
    rectangle_pixels = [(x, y) 
                        for x in range(c_left[0], c_right[0] + 1)
                        for y in range(rectangle_ylimit(c_left, c_right, c_bottom, slope_left_to_bottom, slope_bottom_to_right, x), 
                                       rectangle_ylimit(c_left, c_right, c_top, slope_left_to_top, slope_top_to_right, x) + 1)]
    return rectangle_pixels


def bin_rectangle_optimized(img, p1, p2, rectangle, params):
    """
    Bin intensities of points in the rectangle based on their distance from p1 and p2.
    Calculate vector pointing out of the vesicle, given points proceed clockwise.
    """
    # Unpack relevant params 
    psize = params["psize"]
    hist_offset = params["hist_offset"]

    # Calculate distances of each point in rectangle from line between p1 and p2
    vesicle_normal = np.array([-(p2[1] - p1[1]), (p2[0] - p1[0])]) # Normal vector out of vesicle
    offset = rectangle - np.array(p1) # Vector from p1 to each point in rectangle
    distances = psize * np.dot(offset, vesicle_normal) / np.linalg.norm(vesicle_normal)
    # ERROR HANDLING: Send nan / infinite values to 1000
    distances[~np.isfinite(distances)] = 1000

    # Generate intensities list for distances from -hist_offset to hist_offset
    intensities_by_distance = []
    distances = distances.astype(int) # Round to int for discrete binning
    for distance in range(-hist_offset, hist_offset + 1):
        intensities_at_distance = []
        pixel_indices = rectangle[distances == distance].T
        # ERROR HANDLING: Remove pixels outside image bounds
        pixel_indices = pixel_indices[:, (pixel_indices[0] >= 0) & (pixel_indices[0] < img.shape[1]) & (pixel_indices[1] >= 0) & (pixel_indices[1] < img.shape[0])]
        intensities_at_distance = img[pixel_indices[1], pixel_indices[0]]

        # ERROR HANDLING: Record 0 if no pixels found at this distance
        if len(intensities_at_distance) == 0:
            intensities_by_distance.append(0.0)
        else:
            intensities_by_distance.append(np.mean(intensities_at_distance))
    
    return intensities_by_distance
